#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Multi-cluster, two-stage autoencoder search for cluster-wise gene ranking.

Description
-----------
This script performs autoencoder-based gene ranking for multiple selected clusters
generated by the SignalPath-Finder pipeline. For each cluster, it extracts the
corresponding genes from the expression matrix, standardizes the data, and applies
a two-stage hyperparameter search across multiple random seeds to identify robust
autoencoder configurations. Gene importance is then derived from encoder weights,
and recovery of known downstream genes is evaluated within the top-ranked genes.

Input
-----
1. Cluster assignment file (.csv)
   - Contains gene IDs and their assigned cluster labels.
   - Example: gene_cluster_assignments_CHOSEN_K_seed_x.csv

2. Gene expression matrix (.txt or .tsv)
   - Rows represent genes and columns represent samples.
   - The first column must contain gene IDs.
   - Example: SDX_95_samples.txt

3. Known downstream gene list
   - Provided within the script as KNOWN_DOWNSTREAM_GENES.

Output
------
For each selected cluster, the script generates:
1. Stage A search results across sampled hyperparameter settings
2. Combined Stage A and Stage B master result table
3. Per-seed full gene ranking files
4. Top-5 selected seed summaries
5. Copied ranking files for the top-performing seeds

Additionally, the script produces:
6. A multi-cluster summary file combining the best results across all clusters

Workflow
--------
1. Load cluster assignments and gene expression matrix.
2. Select genes belonging to clusters of interest.
3. Standardize cluster-specific gene expression profiles.
4. Run Stage A random hyperparameter search across multiple seeds.
5. Select top-performing configurations from Stage A.
6. Re-run selected configurations in Stage B using a larger seed range.
7. Compute gene importance scores from encoder-derived weights.
8. Evaluate recovery of known downstream genes among top-ranked genes.
9. Export per-cluster and overall summary results.
"""

import os

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
os.environ.setdefault("TF_NUM_INTRAOP_THREADS", "1")
os.environ.setdefault("TF_NUM_INTEROP_THREADS", "1")
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "")

import hashlib
import random
from concurrent.futures import ProcessPoolExecutor, as_completed
from multiprocessing import cpu_count, get_context

import numpy as np
import pandas as pd
import tensorflow as tf
from scipy.stats import hypergeom
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import Dense, Dropout, GaussianNoise, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l1, l1_l2, l2

tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.threading.set_inter_op_parallelism_threads(1)

# ============================================================================
# User settings
# ============================================================================
CLUSTER_ASSIGNMENT_FILE = "gene_cluster_assignments_CHOSEN_K_seed_x.csv"
EXPR_MATRIX_FILE = "SDX_95_samples.txt"
EXPR_SEP = "\t"

CLUSTERS_OF_INTEREST = [2, 3, 22]
BASE_OUTDIR = "AE_multi_cluster_outputs_fixed_enrichment_seed_x_k_y"

TOTAL_CPUS = min(12, cpu_count())
MAX_CLUSTERS_IN_PARALLEL = 3
TOP_N_MOST_VARIABLE_GENES = None

# ============================================================================
# Known downstream genes
# ============================================================================
KNOWN_DOWNSTREAM_GENES = [
    "Potri.016G138400","Potri.012G016500","Potri.019G043400","Potri.013G075300",
    "Potri.003G205200","Potri.019G010700","Potri.012G004400","Potri.014G107000",
    "Potri.019G056200","Potri.004G200800","Potri.004G200900","Potri.010G115800",
    "Potri.009G018100","Potri.001G220100","Potri.001G142500","Potri.016G090800",
    "Potri.006G127100","Potri.010G186400","Potri.005G162600","Potri.004G059000",
    "Potri.011G068600","Potri.001G301800","Potri.006G102200","Potri.016G119700",
    "Potri.008G191600","Potri.010G039700","Potri.014G031000","Potri.016G081000",
    "Potri.018G139400","Potri.009G148900","Potri.012G091900","Potri.004G188200",
    "Potri.001G386900","Potri.011G106800","Potri.003G026600","Potri.004G062400",
    "Potri.011G071800","Potri.005G083500","Potri.001G298500","Potri.009G093200",
    "Potri.001G251600","Potri.008G068200","Potri.009G046400","Potri.015G012200",
    "Potri.006G180800","Potri.006G109600","Potri.009G129700","Potri.001G099400",
    "Potri.003G132300","Potri.016G104900","Potri.015G020500","Potri.006G209500",
    "Potri.005G137700","Potri.017G111800","Potri.004G103700","Potri.002G059800",
    "Potri.005G202000","Potri.005G109400","Potri.007G063600","Potri.002G050800",
    "Potri.005G211500","Potri.008G154600","Potri.010G085700","Potri.008G174100",
    "Potri.010G062900","Potri.002G099500","Potri.005G072700","Potri.007G096300",
    "Potri.001G311000","Potri.009G161900","Potri.001G417300","Potri.003G205700",
    "Potri.001G018400","Potri.001G007800","Potri.003G217900","Potri.012G107100",
    "Potri.015G106000","Potri.003G162700","Potri.001G031400","Potri.007G113100",
    "Potri.007G037800","Potri.001G309800","Potri.019G007200","Potri.019G011300",
    "Potri.019G011600","Potri.002G181000","Potri.006G092900","Potri.018G103000",
    "Potri.013G000300","Potri.002G096900","Potri.005G164700","Potri.010G071200",
    "Potri.002G179800","Potri.008G046200","Potri.010G215200","Potri.012G005900",
    "Potri.015G002300","Potri.005G114700","Potri.007G012100"
]

KNOWN_DOWNSTREAM_GENE_SET = set(KNOWN_DOWNSTREAM_GENES)

GLOBAL_SEED = 12345

# ============================================================================
# Search settings
# ============================================================================
MAX_TRIALS_STAGE_A = 120
SEEDS_STAGE_A = list(range(1, 51))
TOP_N_FOR_STAGE_B = 10
SEEDS_STAGE_B = list(range(1, 101))

MAX_EPOCHS = 120
ES_PATIENCE = 5
LR_PATIENCE = 3

KDG_THRESHOLD_FOR_DEEP = 3

# ============================================================================
# Parameter grid
# ============================================================================
PARAM_GRID = {
    "encoding_dim": [2, 3, 5, 8, 16, 32],
    "depth": ["shallow", "deep"],
    "activation": ["selu", "relu"],
    "l1_reg": [0.0, 1e-5, 1e-4, 1e-3],
    "l2_reg": [0.0, 1e-5, 1e-4],
    "dropout_rate": [0.0, 0.1, 0.2],
    "noise_sigma": [0.0, 0.05, 0.1],
    "lr": [1e-3, 5e-4, 1e-4],
    "batch_size": [8, 16, 32],
    "top_k": [50],
    "score_type": ["abs-sum", "abs-max"],
}


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    tf.random.set_seed(seed)
    random.seed(seed)


def sample_config(grid: dict) -> dict:
    return {key: random.choice(values) for key, values in grid.items()}


def config_id(params: dict) -> str:
    keys = [
        "encoding_dim",
        "depth",
        "activation",
        "l1_reg",
        "l2_reg",
        "dropout_rate",
        "noise_sigma",
        "lr",
        "batch_size",
        "top_k",
        "score_type",
    ]
    config_string = ";".join(f"{key}={params[key]}" for key in keys)
    return hashlib.md5(config_string.encode("utf-8")).hexdigest()[:10]


def build_autoencoder(input_dim: int, params: dict) -> Model:
    regularizer = None
    if params["l1_reg"] > 0 and params["l2_reg"] > 0:
        regularizer = l1_l2(params["l1_reg"], params["l2_reg"])
    elif params["l1_reg"] > 0:
        regularizer = l1(params["l1_reg"])
    elif params["l2_reg"] > 0:
        regularizer = l2(params["l2_reg"])

    model_input = Input(shape=(input_dim,), name="input")
    x = model_input

    if params["noise_sigma"] > 0:
        x = GaussianNoise(params["noise_sigma"], name="gaussian_noise")(x)
    if params["dropout_rate"] > 0:
        x = Dropout(params["dropout_rate"], name="input_dropout")(x)

    activation = params["activation"]
    encoding_dim = params["encoding_dim"]

    if params["depth"] == "shallow":
        encoded = Dense(
            encoding_dim,
            activation=activation,
            kernel_regularizer=regularizer,
            name="bottleneck",
        )(x)
        decoded = Dense(
            input_dim,
            activation="linear",
            kernel_regularizer=regularizer,
            name="decoder_out",
        )(encoded)
    else:
        hidden_encoder = Dense(
            encoding_dim * 2,
            activation=activation,
            kernel_regularizer=regularizer,
            name="enc_h1",
        )(x)
        encoded = Dense(
            encoding_dim,
            activation=activation,
            kernel_regularizer=regularizer,
            name="bottleneck",
        )(hidden_encoder)
        hidden_decoder = Dense(
            encoding_dim * 2,
            activation=activation,
            kernel_regularizer=regularizer,
            name="dec_h1",
        )(encoded)
        decoded = Dense(
            input_dim,
            activation="linear",
            kernel_regularizer=regularizer,
            name="decoder_out",
        )(hidden_decoder)

    return Model(model_input, decoded, name="AE")


def train_autoencoder(data: pd.DataFrame, params: dict, seed: int) -> tuple[Model, float]:
    set_seed(seed)

    x = data.values.astype(np.float32)
    x_train, x_val = train_test_split(x, test_size=0.2, random_state=seed, shuffle=True)

    model = build_autoencoder(x.shape[1], params)
    model.compile(optimizer=Adam(learning_rate=params["lr"]), loss="mse")

    callbacks = [
        EarlyStopping(monitor="val_loss", patience=ES_PATIENCE, restore_best_weights=True),
        ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=LR_PATIENCE, min_lr=1e-6),
    ]

    model.fit(
        x_train,
        x_train,
        validation_data=(x_val, x_val),
        epochs=MAX_EPOCHS,
        batch_size=params["batch_size"],
        verbose=0,
        callbacks=callbacks,
    )

    x_hat = model.predict(x_val, verbose=0)
    val_mse = float(np.mean((x_val - x_hat) ** 2))
    return model, val_mse


def compute_gene_importance(model: Model, genes: list[str], score_type: str) -> pd.Series:
    try:
        w_input_to_h1 = model.get_layer("enc_h1").get_weights()[0]
        w_h1_to_bottleneck = model.get_layer("bottleneck").get_weights()[0]
        kernel = w_input_to_h1 @ w_h1_to_bottleneck
    except ValueError:
        kernel = model.get_layer("bottleneck").get_weights()[0]

    kernel = np.nan_to_num(kernel, nan=0.0, posinf=0.0, neginf=0.0)
    if kernel.shape[0] != len(genes):
        raise ValueError(f"Kernel rows {kernel.shape[0]} do not match number of genes {len(genes)}.")

    weights = pd.DataFrame(kernel, index=genes)

    if score_type == "abs-sum":
        importance = weights.abs().sum(axis=1)
    elif score_type == "abs-max":
        importance = weights.abs().max(axis=1)
    else:
        raise ValueError(f"Unknown score type: {score_type}")

    return importance.sort_values(ascending=False)


def evaluate_recovery(importance: pd.Series, known_downstream_genes: list[str], top_k: int) -> dict:
    """
    Evaluate recovery of known downstream genes by restricting the reference list
    to the ranked gene universe before computing expected counts, fold enrichment,
    and hypergeometric p-values.
    """
    top_k = min(top_k, len(importance))
    top_genes = set(importance.head(top_k).index)
    universe = set(importance.index)
    n_universe = len(universe)

    reference = set(known_downstream_genes) & universe
    k_universe = len(reference)
    k_top = len(top_genes & reference)
    expected = (top_k * k_universe / n_universe) if n_universe > 0 else np.nan
    fold = (k_top / expected) if (expected and expected > 0) else np.nan

    if k_universe == 0 or n_universe == 0:
        p_value = 1.0
    else:
        p_value = 1 - hypergeom.cdf(k_top - 1, n_universe, k_universe, top_k)

    return {
        "kdg_topk": k_top,
        "kdg_fold_enrichment": fold,
        "kdg_expected": expected,
        "kdg_p_value": p_value,
        "kdg_in_universe": k_universe,
        "n_universe": n_universe,
    }


def save_full_ranking(importance: pd.Series, out_path: str, top_k: int) -> None:
    ranks = np.arange(1, len(importance) + 1, dtype=int)
    genes = importance.index.to_numpy()

    is_kdg = np.isin(genes, list(KNOWN_DOWNSTREAM_GENE_SET))
    in_top_k = ranks <= min(top_k, len(importance))

    pd.DataFrame(
        {
            "gene": genes,
            "score": importance.values,
            "rank": ranks,
            "in_topk": in_top_k,
            "is_known_downstream_gene": is_kdg,
            "label": np.where(is_kdg, "KDG", "None"),
        }
    ).to_csv(out_path, index=False)


def run_one_seed(args: tuple) -> dict:
    seed, params, genes, data, per_seed_dir = args
    tf.config.threading.set_intra_op_parallelism_threads(1)
    tf.config.threading.set_inter_op_parallelism_threads(1)

    cfg_id = config_id(params)
    rank_path = os.path.join(per_seed_dir, f"{cfg_id}__seed-{seed}.csv")

    model, val_mse = train_autoencoder(data, params, seed)
    importance = compute_gene_importance(model, genes, params["score_type"])
    save_full_ranking(importance, rank_path, params["top_k"])

    recovery_stats = evaluate_recovery(importance, KNOWN_DOWNSTREAM_GENES, params["top_k"])

    return {
        **params,
        "seed": seed,
        "val_mse": val_mse,
        **recovery_stats,
        "rank_path": rank_path,
        "config_id": cfg_id,
    }


def load_cluster_assignments(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    lowercase_columns = {column.lower(): column for column in df.columns}

    gene_candidates = ["gene", "gene_id", "genes", "id", "attribution"]
    cluster_candidates = ["cluster", "cluster_id", "kmeans_cluster", "label"]

    gene_col = next((lowercase_columns[c] for c in gene_candidates if c in lowercase_columns), None)
    cluster_col = next((lowercase_columns[c] for c in cluster_candidates if c in lowercase_columns), None)

    if gene_col is None:
        raise ValueError(f"Could not identify a gene column in {path}. Columns: {list(df.columns)}")
    if cluster_col is None:
        raise ValueError(f"Could not identify a cluster column in {path}. Columns: {list(df.columns)}")

    assignments = df[[gene_col, cluster_col]].copy()
    assignments.columns = ["gene", "cluster"]
    return assignments


def load_expression_matrix(path: str, sep: str) -> pd.DataFrame:
    df = pd.read_csv(path, sep=sep)
    first_column = df.columns[0]
    return df.rename(columns={first_column: "gene"}).set_index("gene")


def run_cluster_pipeline(
    cluster_id: int,
    cluster_genes: list[str],
    expr_df: pd.DataFrame,
    outdir: str,
    pool_procs: int,
) -> dict:
    cluster_dir = os.path.join(outdir, f"cluster_{cluster_id:03d}")
    os.makedirs(cluster_dir, exist_ok=True)

    stage_a_file = os.path.join(cluster_dir, f"AE_stageA_results_cluster_{cluster_id}.csv")
    master_file = os.path.join(cluster_dir, f"AE_master_grid_results_cluster_{cluster_id}.csv")

    per_seed_dir = os.path.join(cluster_dir, "per_seed_ranks")
    top5_dir = os.path.join(cluster_dir, "top5_seeds")
    os.makedirs(per_seed_dir, exist_ok=True)
    os.makedirs(top5_dir, exist_ok=True)

    top5_summary_file = os.path.join(top5_dir, f"top5_seeds_cluster_{cluster_id}_summary.csv")

    genes_in_expr = expr_df.index.intersection(cluster_genes)
    if len(genes_in_expr) < 10:
        return {
            "cluster": cluster_id,
            "status": "SKIP",
            "reason": f"Too few genes after filtering: {len(genes_in_expr)}",
        }

    subset = expr_df.loc[genes_in_expr].copy()
    data = subset.T

    data = (data - data.mean(axis=0)) / data.std(axis=0, ddof=0)
    data = data.replace([np.inf, -np.inf], np.nan).fillna(0.0)

    if TOP_N_MOST_VARIABLE_GENES is not None:
        variances = data.var(axis=0, ddof=0)
        keep_genes = variances.nlargest(TOP_N_MOST_VARIABLE_GENES).index
        data = data[keep_genes]

    genes = data.columns.tolist()
    context = get_context("spawn")

    set_seed(GLOBAL_SEED)

    stage_a_rows = []
    for trial in range(MAX_TRIALS_STAGE_A):
        params = sample_config(PARAM_GRID)
        requested_depth = params["depth"]

        shallow_params = params.copy()
        shallow_params["depth"] = "shallow"

        with context.Pool(processes=pool_procs) as pool:
            jobs = [(seed, shallow_params, genes, data, per_seed_dir) for seed in SEEDS_STAGE_A]
            shallow_runs = pool.map(run_one_seed, jobs, chunksize=1)
        stage_a_rows.extend(shallow_runs)

        mean_kdg = float(np.mean([result["kdg_topk"] for result in shallow_runs]))

        if requested_depth == "deep" and mean_kdg >= KDG_THRESHOLD_FOR_DEEP:
            deep_params = params.copy()
            deep_params["depth"] = "deep"
            with context.Pool(processes=pool_procs) as pool:
                jobs = [(seed, deep_params, genes, data, per_seed_dir) for seed in SEEDS_STAGE_A]
                deep_runs = pool.map(run_one_seed, jobs, chunksize=1)
            stage_a_rows.extend(deep_runs)

        if (trial + 1) % 10 == 0:
            print(f"[cluster {cluster_id}] Stage A trials: {trial + 1}/{MAX_TRIALS_STAGE_A} (pool={pool_procs})")

    df_stage_a = pd.DataFrame(stage_a_rows)
    df_stage_a.to_csv(stage_a_file, index=False)
    print(f"[cluster {cluster_id}] Stage A saved: {stage_a_file}")

    group_columns = [
        "encoding_dim",
        "depth",
        "activation",
        "l1_reg",
        "l2_reg",
        "dropout_rate",
        "noise_sigma",
        "lr",
        "batch_size",
        "top_k",
        "score_type",
    ]

    aggregated = (
        df_stage_a.groupby(group_columns)[["kdg_topk"]]
        .mean()
        .sort_values(["kdg_topk"], ascending=False)
    )
    top_configs = aggregated.head(TOP_N_FOR_STAGE_B).reset_index().to_dict(orient="records")

    stage_b_rows = []
    for params_cfg in top_configs:
        with context.Pool(processes=pool_procs) as pool:
            jobs = [(seed, params_cfg, genes, data, per_seed_dir) for seed in SEEDS_STAGE_B]
            config_results = pool.map(run_one_seed, jobs, chunksize=1)
        stage_b_rows.extend(config_results)
        print(f"[cluster {cluster_id}] Stage B complete for one configuration ({len(SEEDS_STAGE_B)} seeds).")

    df_stage_b = pd.DataFrame(stage_b_rows)

    df_all = pd.concat([df_stage_a, df_stage_b], ignore_index=True)
    df_all.to_csv(master_file, index=False)
    print(f"[cluster {cluster_id}] Master results saved: {master_file}")

    mse_min = float(df_all["val_mse"].min())
    mse_std = float(df_all["val_mse"].std(ddof=0))
    mse_cutoff = mse_min + mse_std

    df_filtered = df_all[df_all["val_mse"] <= mse_cutoff].copy()
    if df_filtered.empty:
        df_filtered = df_all.copy()

    df_sorted = df_filtered.sort_values(
        ["kdg_topk", "kdg_fold_enrichment", "val_mse"],
        ascending=[False, False, True]
    ).reset_index(drop=True)

    df_top5 = df_sorted.head(5).copy()

    keep_columns = [
        "seed",
        "val_mse",
        "kdg_topk",
        "kdg_fold_enrichment",
        "kdg_p_value",
        "kdg_expected",
        "kdg_in_universe",
        "n_universe",
        "config_id",
        "rank_path",
        *group_columns,
    ]

    df_top5_summary = df_top5[keep_columns]
    df_top5_summary.to_csv(top5_summary_file, index=False)

    for _, row in df_top5_summary.iterrows():
        src = row.get("rank_path", "")
        if isinstance(src, str) and os.path.isfile(src):
            destination = os.path.join(top5_dir, os.path.basename(src))
            try:
                pd.read_csv(src).to_csv(destination, index=False)
            except Exception:
                pass

    best = df_top5_summary.iloc[0].to_dict() if len(df_top5_summary) else {}
    return {
        "cluster": cluster_id,
        "status": "OK",
        "n_genes": len(genes),
        "mse_cut": mse_cutoff,
        "best_seed": best.get("seed"),
        "best_kdg_topk": best.get("kdg_topk"),
        "best_kdg_fold_enrichment": best.get("kdg_fold_enrichment"),
        "best_kdg_p_value": best.get("kdg_p_value"),
        "kdg_in_universe_best": best.get("kdg_in_universe"),
        "cluster_dir": cluster_dir,
    }


def main() -> None:
    os.makedirs(BASE_OUTDIR, exist_ok=True)

    assignments = load_cluster_assignments(CLUSTER_ASSIGNMENT_FILE)
    assignments["cluster"] = pd.to_numeric(assignments["cluster"], errors="coerce")
    assignments = assignments.dropna(subset=["cluster"])
    assignments["cluster"] = assignments["cluster"].astype(int)

    expr = load_expression_matrix(EXPR_MATRIX_FILE, EXPR_SEP)

    max_parallel = max(1, int(MAX_CLUSTERS_IN_PARALLEL))
    total_cpus = max(1, int(TOTAL_CPUS))
    cpus_per_cluster = max(1, total_cpus // max_parallel)

    print(
        f"TOTAL_CPUS={total_cpus} | "
        f"MAX_CLUSTERS_IN_PARALLEL={max_parallel} | "
        f"CPUS_PER_CLUSTER={cpus_per_cluster}"
    )
    print(f"Clusters requested: {CLUSTERS_OF_INTEREST}")
    print(f"Expression genes: {expr.shape[0]} | Samples: {expr.shape[1]}")

    jobs = []
    for cluster_id in CLUSTERS_OF_INTEREST:
        cluster_genes = (
            assignments.loc[assignments["cluster"] == int(cluster_id), "gene"]
            .astype(str)
            .unique()
            .tolist()
        )
        jobs.append((int(cluster_id), cluster_genes))

    results = []
    with ProcessPoolExecutor(max_workers=max_parallel) as executor:
        futures = [
            executor.submit(run_cluster_pipeline, cluster_id, cluster_genes, expr, BASE_OUTDIR, cpus_per_cluster)
            for cluster_id, cluster_genes in jobs
        ]

        for future in as_completed(futures):
            try:
                result = future.result()
                results.append(result)

                best_fold = result.get("best_kdg_fold_enrichment")
                best_fold_str = f"{best_fold:.3f}" if best_fold is not None else "NA"

                best_p = result.get("best_kdg_p_value")
                best_p_str = f"{best_p:.2e}" if best_p is not None else "NA"

                print(
                    f"[DONE] cluster={result.get('cluster')} "
                    f"status={result.get('status')} "
                    f"best_kdg_topk={result.get('best_kdg_topk')} "
                    f"best_kdg_fold={best_fold_str} "
                    f"best_kdg_p={best_p_str} "
                    f"dir={result.get('cluster_dir')}"
                )
            except Exception as exc:
                print(f"[ERROR] Cluster job failed: {exc}")

    summary_path = os.path.join(BASE_OUTDIR, "multi_cluster_summary.csv")
    pd.DataFrame(results).to_csv(summary_path, index=False)
    print(f"Multi-cluster summary saved: {summary_path}")


if __name__ == "__main__":
    main()